/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IValidationModule,
  IValidationModuleInterface,
} from "../../../contracts/modules/IValidationModule";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "arg",
        type: "bytes",
      },
    ],
    name: "validate",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IValidationModule__factory {
  static readonly abi = _abi;
  static createInterface(): IValidationModuleInterface {
    return new Interface(_abi) as IValidationModuleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IValidationModule {
    return new Contract(address, _abi, runner) as unknown as IValidationModule;
  }
}
