/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as kintoCountryValidatorModuleSol from "./KintoCountryValidatorModule.sol";
export type { kintoCountryValidatorModuleSol };
import type * as privadoIdValidatorModuleSol from "./PrivadoIDValidatorModule.sol";
export type { privadoIdValidatorModuleSol };
import type * as worldcoinValidatorModuleSol from "./WorldcoinValidatorModule.sol";
export type { worldcoinValidatorModuleSol };
export type { IValidationModule } from "./IValidationModule";
export type { TestValidatorModule } from "./TestValidatorModule";
