/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface EarlyAccessCodesTestContractInterface extends Interface {
  getFunction(
    nameOrSignature: "earlyAccessCodes" | "testFunction"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Success"): EventFragment;

  encodeFunctionData(
    functionFragment: "earlyAccessCodes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testFunction",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "earlyAccessCodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testFunction",
    data: BytesLike
  ): Result;
}

export namespace SuccessEvent {
  export type InputTuple = [success: boolean];
  export type OutputTuple = [success: boolean];
  export interface OutputObject {
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EarlyAccessCodesTestContract extends BaseContract {
  connect(runner?: ContractRunner | null): EarlyAccessCodesTestContract;
  waitForDeployment(): Promise<this>;

  interface: EarlyAccessCodesTestContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  earlyAccessCodes: TypedContractMethod<[], [string], "view">;

  testFunction: TypedContractMethod<
    [
      _commitment: BytesLike,
      _proof: BytesLike,
      _root: BytesLike,
      _nullifierHash: BytesLike,
      _validationsArgs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "earlyAccessCodes"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "testFunction"
  ): TypedContractMethod<
    [
      _commitment: BytesLike,
      _proof: BytesLike,
      _root: BytesLike,
      _nullifierHash: BytesLike,
      _validationsArgs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Success"
  ): TypedContractEvent<
    SuccessEvent.InputTuple,
    SuccessEvent.OutputTuple,
    SuccessEvent.OutputObject
  >;

  filters: {
    "Success(bool)": TypedContractEvent<
      SuccessEvent.InputTuple,
      SuccessEvent.OutputTuple,
      SuccessEvent.OutputObject
    >;
    Success: TypedContractEvent<
      SuccessEvent.InputTuple,
      SuccessEvent.OutputTuple,
      SuccessEvent.OutputObject
    >;
  };
}
