/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BetaProtocol__factory } from "./BetaProtocol__factory";
export { IWhitelist__factory } from "./IWhitelist__factory";
