/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as betaProtocolSol from "./BetaProtocol.sol";
export type { betaProtocolSol };
export type { TestProtocol } from "./TestProtocol";
export type { Whitelist } from "./Whitelist";
export type { WhitelistFactory } from "./WhitelistFactory";
