/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface WhitelistFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "changeDefaultHasher"
      | "changeDefaultMerkleTreeHeight"
      | "changeDefaultVerifier"
      | "create"
      | "createTalariaInstance"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OwnershipTransferred" | "WhitelistCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "changeDefaultHasher",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changeDefaultMerkleTreeHeight",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeDefaultVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "create", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createTalariaInstance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "changeDefaultHasher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeDefaultMerkleTreeHeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeDefaultVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createTalariaInstance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistCreatedEvent {
  export type InputTuple = [whitelist: AddressLike];
  export type OutputTuple = [whitelist: string];
  export interface OutputObject {
    whitelist: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WhitelistFactory extends BaseContract {
  connect(runner?: ContractRunner | null): WhitelistFactory;
  waitForDeployment(): Promise<this>;

  interface: WhitelistFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  changeDefaultHasher: TypedContractMethod<
    [_newHasher: AddressLike],
    [void],
    "nonpayable"
  >;

  changeDefaultMerkleTreeHeight: TypedContractMethod<
    [_newMerkleTreeHeight: BigNumberish],
    [void],
    "nonpayable"
  >;

  changeDefaultVerifier: TypedContractMethod<
    [_newVerifier: AddressLike],
    [void],
    "nonpayable"
  >;

  create: TypedContractMethod<[], [string], "nonpayable">;

  createTalariaInstance: TypedContractMethod<[], [string], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "changeDefaultHasher"
  ): TypedContractMethod<[_newHasher: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "changeDefaultMerkleTreeHeight"
  ): TypedContractMethod<
    [_newMerkleTreeHeight: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "changeDefaultVerifier"
  ): TypedContractMethod<[_newVerifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "create"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "createTalariaInstance"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistCreated"
  ): TypedContractEvent<
    WhitelistCreatedEvent.InputTuple,
    WhitelistCreatedEvent.OutputTuple,
    WhitelistCreatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "WhitelistCreated(address)": TypedContractEvent<
      WhitelistCreatedEvent.InputTuple,
      WhitelistCreatedEvent.OutputTuple,
      WhitelistCreatedEvent.OutputObject
    >;
    WhitelistCreated: TypedContractEvent<
      WhitelistCreatedEvent.InputTuple,
      WhitelistCreatedEvent.OutputTuple,
      WhitelistCreatedEvent.OutputObject
    >;
  };
}
