/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as betaProtocolSol from "./BetaProtocol.sol";
export { TestProtocol__factory } from "./TestProtocol__factory";
export { Whitelist__factory } from "./Whitelist__factory";
export { WhitelistFactory__factory } from "./WhitelistFactory__factory";
