/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../../common";
import type {
  ExecutorOptions,
  ExecutorOptionsInterface,
} from "../../../../../../@layerzerolabs/lz-evm-protocol-v2/contracts/messagelib/libs/ExecutorOptions";

const _abi = [
  {
    inputs: [],
    name: "Executor_InvalidLzComposeOption",
    type: "error",
  },
  {
    inputs: [],
    name: "Executor_InvalidLzReceiveOption",
    type: "error",
  },
  {
    inputs: [],
    name: "Executor_InvalidNativeDropOption",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220e824fe28c90d8455fb6c8233d6aa3d2833e0107cc5dc361a108fbf73606d12ec64736f6c63430008140033";

type ExecutorOptionsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ExecutorOptionsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ExecutorOptions__factory extends ContractFactory {
  constructor(...args: ExecutorOptionsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ExecutorOptions & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ExecutorOptions__factory {
    return super.connect(runner) as ExecutorOptions__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ExecutorOptionsInterface {
    return new Interface(_abi) as ExecutorOptionsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ExecutorOptions {
    return new Contract(address, _abi, runner) as unknown as ExecutorOptions;
  }
}
